### ISSUE TITLE
Layout de pantalla de puntajes

### ISSUE THREAD

**Issue by diegocode** [PioIX/ProyectoInterGrupo7#19]
En la pantalla de puntajes, en una pantalla con resolución 1366x768 (bastante común) , la lista de jugadores queda sobre el footer

![image](https://user-images.githubusercontent.com/13907164/186721772-d1a67983-1651-4f35-a0bf-fa39a9526379.png)

**Comment by CelesRod** [comment]
ya lo agregamos haciendo que la altura del rectángulo sea :auto.
